---
archs:
  - arm64
package:
  name: go-hello-world
  version: 0.0.2
  epoch: 0
  description: "a simple hello world rest api used for demos"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: Apache License 2.0
  dependencies:
    runtime:
environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
  packages: {}
pipeline:
  - name: install hello world
    uses: go/install
    with:
      package: github.com/kameshsampath/go-hello-world
      version: v${{package.version}}
